### ISSUE TITLE
Upgrade to latest Docus

### ISSUE THREAD

**Issue by Atinux** [nuxt-modules/html-validator#181]
Would you mind doing this @smarroufin?

**Comment by Atinux** [comment]
I think first we need to support Nuxt 3 for this module. @danielroe any blockers right now for not support N3?

**Comment by danielroe** [comment]
Currently waiting on https://github.com/nuxt/framework/issues/5534.

**Comment by danielroe** [comment]
We now support nuxt 3 :+1:
