### ISSUE TITLE
docs: code groups are broken

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/html-validator#226]
Currently, code groups on this module's documentation page are broken:
![image](https://user-images.githubusercontent.com/4778485/193957510-27a94f27-ce8a-46d2-9742-e9b2da4a990b.png)
I know that there is ticket #181, but I wonder why code groups stopped working with nuxt content v1. Maybe there is an upstream ticket already that I do not find?

**Comment by danielroe** [comment]
should be resolved in https://github.com/nuxt-modules/html-validator/pull/173
