### ISSUE TITLE
Typescript hook name errors not picked up by eslint

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/html-validator#248]
On the current master inside the `module.ts` file there are typescript errors for [L58](https://github.com/nuxt-modules/html-validator/blob/6275aa333cd7595a0064d55727b196fd4336dc4e/src/module.ts#L58), L74 and L75. They only show to me in VSCode though, not at `yarn lint:all`.
I'd expect the linting to fail.

**Comment by danielroe** [comment]
These are not lint errors but TS errors which would cause the build to fail.
