### ISSUE TITLE
How to ignore or fix warnings for SSG fallback pages

### ISSUE THREAD

**Issue by PatrikBird** [nuxt-modules/html-validator#346]
Hey!

Thanks for this nice module which helped me a lot cleaning up my html!

I am using Nuxt3 + Content2 and _nuxi generate_ and therefore 200.html and 404.html pages are being created as fallback. 
Those are required for "wildcard" pages like [slug].vue, **right? correct me if I am wrong.**

Those pages throw warnings while using this module as they miss the _lang_ attribute in their html, which is not a big deal to begin with but I am wondering how I can either ignore the warnings (just for those two files) or add those tags to the fallback pages.

**Comment by danielroe** [comment]
Have you tried setting it in the `app.head` section of your Nuxt config file?

**Comment by PatrikBird** [comment]
> Have you tried setting it in the `app.head` section of your Nuxt config file?

yep, it works.. thanks a bunch! 

FYI:
I only used the 
```html
<Html lang="en" />
```
Component in my layout.. hence the fallbacks don't have the attribute.
