### ISSUE TITLE
ignore 404.html and 505.html when running nuxt generate

### ISSUE THREAD

**Issue by thunfisch987** [nuxt-modules/html-validator#402]
Hi, 
nuxt generate fails for me because it finds errors in 200.html and 404.html, is there any way to disable checking these?
Or is this something that has to be fixed in the nuxt repository?

_**I have Tailwind installed per @nuxtjs/tailwindcss**_, might that be the problem?
```
 ERROR  HTML validation errors found for /404.html
error: <style> element is not permitted as content under <div> (element-permitted-content) at inline:2325:9:
  2323 |           d="M24.236 22.006h10.742L25.563 5.822l-8.979 14.31a4 4 0 0 1-3.388 1.874H2.978l11.631-20 5.897 10.567"
  2324 |         ></path></svg
> 2325 |       ><style>
       |         ^^^^^
  2326 |         .nuxt-spa-loading {
  2327 |           position: fixed;
  2328 |           top: 50%;
Details: https://html-validate.org/rules/element-permitted-content.html
```

**Comment by dargmuesli** [comment]
I've created an issue that explains why this error pops up: https://github.com/nuxt/nuxt/issues/22526 (tailwind is not the problem).
Besides that, the possibility to ignore certain paths would certainly be a cool addition! :rocket:

**Comment by thunfisch987** [comment]
https://github.com/nuxt/assets/issues/216#issuecomment-1719762319

**Comment by thunfisch987** [comment]
https://github.com/nuxt/assets/issues/216#issuecomment-1719762319
