### ISSUE TITLE
No html-validator.nuxtjs.org links work

### ISSUE THREAD

**Issue by SuperNickkk** [nuxt-modules/html-validator#476]
Well, it's all in the title.

On the website:
https://nuxt.com/modules/html-validator

None of the links to the html-validator.nuxtjs.org domain work.  No content is displayed in Firefox, Chrome or Vivaldi.

### Version

n/a

### Nuxt configuration

na/

### Nuxt configuration

n/a

## Reproduction

This concerns the websites not the modules!

#### What is expected?

the relevant webpage should show in the browser.

On https://nuxt.com/modules/html-validator

click:
Release Notes >> https://html-validator.nuxtjs.org/releases
Documentation >> https://html-validator.nuxtjs.org/
Read More >> https://html-validator.nuxtjs.org/

The same is true for https://www.npmjs.com/package/@nuxtjs/html-validator

And for https://github.com/nuxt-modules/html-validator

#### What is actually happening?

You just get a blank web page.

#### Steps to reproduce

Just try clicking the links!

## Checklist

* [x ]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by lt-tim** [comment]
Have the same issue

**Comment by sathish099** [comment]
still not available on the website:
https://nuxt.com/modules/html-validator @danielroe

**Comment by danielroe** [comment]
we're back up now!

https://html-validator.nuxtjs.org/
