### ISSUE TITLE
How to switch between development and production environments?

### ISSUE THREAD

**Issue by martinadamsdev** [nuxt-modules/html-validator#535]
## Problem:
After I use the plugin I can't differentiate between development and production environments.

```typescript
modules: [
    ...
    '@nuxtjs/html-validator',
],

htmlValidator: {
  usePrettier: true,
  ignore: [/\.(xml|rss|json)$/],
  ...
},
```

## Expected:
- When packaging for production, I want to skip all html-validator checks.
- I can enable `@nuxtjs/html-validator` checks in the development environment.

```typescript
modules: [
    ...
    '@nuxtjs/html-validator',
],

htmlValidator: {
  enabled: true, // or false
  ...
},
```

**Comment by danielroe** [comment]
You can use:

```ts
export default defineNuxtConfig({
  $production: {
    htmlValidator: {
      enabled: false,
    },
  }
})
```

**Comment by danielroe** [comment]
it seems it didn't! now implemented.

**Comment by danielroe** [comment]
😆 

bonk them on the nose and tell them to enter alt text
